# Generated by Django 6.0.2 on 2026-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.AlterField(
            model_name='submission',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
